---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---
```{r Long Run}
basePath <- "G:/Hanna/SimulationTree/selection_false/translMethod_affinity/"
configPath <- paste(basePath, "configLongRun.csv", sep = "")
configLongRun <- data.table::fread(configPath)
colnames(configLongRun) <- c("translationType", "mrnaSeed", "codonNumb", "geneLength", "geneNumb", "mrnaId", "initAaNumb", "similarAars", "maxAnticodonNumb", "aarsLifeticksStartValue", "livingAarsStartNumb", "livingAarsSeed", "outputSeed", "addToOutput", "mrnaPath", "aarsPath", "livingAarsPath", "livingAarsDir")
  #get paths
  outputPath <- paste(configLongRun$livingAarsDir, paste("output_s", configLongRun$outputSeed, sep = ""), sep = "")
  fitnessPaths <- paste(outputPath, "codeTableFitness.csv", sep = "\\")
  # read fitness values from paths
  fitnessLongRun <- c()
  for(row in 1:length(fitnessPaths)){
    fitnessLongRun[row] <- data.table::fread(fitnessPaths[row], integer64= "double")
    fitnessLongRun[row] <- tail(fitnessLongRun[row], length(fitnessLongRun[row])-20)
  }
  summary(fitnessLongRun)
  boxplot(tail(fitnessLongRun, length(fitnessLongRun)-20))

```

```{r init libraries}
library(flextable)
library(data.table)
library(igraph)
library(descr)
```


```{r init base variables}
config <- c()
fitness <- c()
fitnessPaths <- c()
```


```{r read data}
newConfig <- c()
newFitness <- c()
counted <- data.table()
fitnessIds <- c()
lengths <- c()
values <- c()

# read config
  basePath <- "G:/Hanna/SimulationTree/selection_false/translMethod_affinity/"
  configPath1 <- paste(basePath, "config_64_48_3_2.csv", sep = "")
  basePath <- "G:/Hanna/SimulationTree/selection_false/translMethod_random/"
  #configPath2 <- paste(basePath, "config.csv", sep = "")
  basePath <- "G:/Hanna/SimulationTree/selection_false/translMethod_max/"
  #configPath3 <- paste(basePath, "config.csv", sep = "")
  #configPath <- rbind(configPath1, configPath2, configPath3)
  #newConfig <- apply(configPath, FUN = function(path){data.table::fread(path)}, MARGIN = 1)
  newConfig <- data.table::fread(configPath1)
  
  # set column names
  colnames(newConfig) <- c("translationType", "mrnaSeed", "codonNumb", "geneLength", "geneNumb", "mrnaId", "initAaNumb", "similarAars", "maxAnticodonNumb", "aarsLifeticksStartValue", "livingAarsStartNumb", "livingAarsSeed", "outputSeed", "addToOutput", "mrnaPath", "aarsPath", "livingAarsPath", "livingAarsDir")
  
  #get fitness paths
  outputPath <- paste(newConfig$livingAarsDir, paste("output_s", newConfig$outputSeed, sep = ""), sep = "")
  fitnessPaths <- paste(outputPath, "codeTableFitness.csv", sep = "\\")
  
  # read fitness values from paths
  fitnessPathsLength <- length(fitnessPaths)
  fPathsToProcess <- fitnessPaths
  maxToTake <- 46080
  if (fitnessPathsLength > maxToTake){
    fPathsToProcess <- head(fitnessPaths, maxToTake)
    fitnessPaths <- tail(fitnessPaths, fitnessPathsLength - maxToTake)
  }
  indices <- c(1:length(fPathsToProcess))
  newFitness <- sapply(indices, FUN = function (pos){data.table::fread(fPathsToProcess[pos])})
  fitness <- c(fitness, newFitness)
  
  
  #summarize fitness data
  indices <- c(1:length(fitness))
  descrStatistics <- sapply(indices, FUN = function(pos){summary(fitness[[pos]])})
  descrStatistics <- data.table(t(descrStatistics))
  
  #add descriptive statistics to newConfig
  newConfig <- cbind(descrStatistics, newConfig)
  
  #count number of generations that the cell lived
  notNullValues <- sapply(indices,FUN =  function(pos){length(which((fitness[[pos]] > 0) == TRUE))})
  newConfig <- cbind(notNullValues, newConfig)
  
  #add numberof simulation steps per param combination
  simulationSteps <- sapply(indices, FUN = function(pos){length(fitness[[pos]])})
  newConfig <- cbind(simulationSteps, newConfig)

  max(newConfig$notNullValue[which(newConfig$simulationSteps != newConfig$notNullValues)])
  newConfig[which(newConfig$notNullValues == 99555)]
  plot(unique(newConfig$notNullValue[which(newConfig$simulationSteps != newConfig$notNullValues)]))
  rle(newConfig$notNullValues[which(newConfig$notNullValues == newConfig$aarsLifeticksStartValue & newConfig$simulationSteps != newConfig$notNullValues)])
  # set up the plot 
plot(c(2000:100000), c(2000:100000), type="n", xlab="Age (days)",
     ylab="Circumference (mm)" ) 
    lines(newConfig$simulationSteps,newConfig$notNullValues, type="b", lwd=1.5) 
    hist(newConfig$notNullValues[which(newConfig$notNullValues< 1000)])
    
    hist(newConfig$notNullValues[which(newConfig$notNullValues< 50 & newConfig$notNullValues > 0)], breaks = 50, col = c("darkGreen", "red"))
    
    newConfig$geneNumb <- factor(newConfig$geneNumb, ordered = TRUE)
    table(newConfig$geneNumb)
    barplot(table(newConfig$geneNumb))
    
    summary(newConfig)
    
    plot(factor(newConfig$geneNumb), newConfig$Mean)
    
    
    
    
par(mfrow=c(1,1)) # all plots on one page 
 plot(factor(newConfig$livingAarsStartNumb), newConfig$Mean)
 plot(factor(newConfig$aarsLifeticksStartValue), newConfig$Mean)
 plot(factor(newConfig$codonNumb), newConfig$Mean)
 plot(factor(newConfig$geneNumb), newConfig$Mean)
 plot(factor(newConfig$initAaNumb), newConfig$Mean)
 plot(factor(newConfig$maxAnticodonNumb), newConfig$Mean)
 plot(factor(newConfig$similarAars), newConfig$Mean)
 plot(factor(newConfig$simulationSteps), newConfig$Mean)
 
 
 
boxplot(newConfig$Mean ~ factor(newConfig$geneNumb))
means <- by(newConfig$Mean, factor(newConfig$geneNumb), mean) 
points(1:8, means, pch = 10, cex = 0.75, bg = "red")
text(1:8 - 0.5, means, labels = formatC(means, format = "f", digits = 2), pos = 4, cex = 0.9, col = "red")
 



# Create Line Chart

# convert factor to numeric for convenience 
factor1 <- as.numeric(factor(newConfig$codonNumb))
ntrees <- max(factor1)

# get the range for the x and y axis 
xrange <- range(newConfig$Mean) 
yrange <- range(newConfig$livingAarsStartNumb) 

# set up the plot 
plot(xrange, yrange, type="n", xlab="Mean",
   ylab="livingAarsStartNumb" ) 
colors <- rainbow(ntrees) 
linetype <- c(1:ntrees) 
plotchar <- seq(18,18+ntrees,1)

# add lines 
for (i in 1:ntrees) { 
  tree <- subset(newConfig, factor1==i) 
  lines(tree$Mean, tree$livingAarsStartNumb, type="o", lwd=1.5,
    lty=linetype[i], col=colors[i], pch=plotchar[i]) 
} 

# add a title and subtitle 
title("Tree Growth", "example of line plot")

# add a legend 
legend(xrange[1], yrange[2], levels(factor(newConfig$codonNumb)), cex=0.8, col=colors,
   pch=plotchar, lty=linetype, title="Tree")











    # if cell didn't die
    if(notNullValues == length(fitnessValues)){
      # check if there are repetitive values
      rleResult <- rle(fitnessValues)
      fitnessIds <- row
      lengths[row] <- rleResult$lengths
      values[row] <- rleResults$values
      
      #counted$values[counted$lengths != 1]
      fitness[[row]] <- tail(fitnessValue, length(fitnessValue)-20)
    }else{
      fitness[[row]] <- fitnessValues[which(fitnessValues > 0)]
    }
  }
  counted <- data.table("fitnessIds" = fitnessIds, "lengths" = lengths, "values" = values)


  # add summary
  sum <- c()
  for(row in 1:length(fitness)){
    sum <- rbind(sum, summary(fitness[[row]]))
  }
newConfig <- cbind(newConfig, sum)
#newConfig <- cbind(data.table("ids" = (length(config)+1):((length(config)+1)+nrow(newConfig))), newConfig)

```
```{r add new data}
config <- rbind(newConfig)

```

```{r graph}
graphData <- unique(data.table("h" = newConfig$initAaNumb, "m" = newConfig$codonNumb))
graphData <- as.matrix(graphData)
graphData <- graph.edgelist(graphData)
V(graphData) # vertices
E(graphData) # edges
gsize(graphData) # number of edges
gorder(graphData) # number of vertices
plot(graphData)
plot(induced_subgraph(graphData, c(3,4,8,10,16,20, 48,64,1,2,5)))
plot(induced_subgraph(graphData, c(48,64, 20, 16,8)))
set_vertex_attr(graphData, "initAaNumb", value = newConfig$initAaNumb)
set_vertex_attr(graphData, "codonNumb", value = newConfig$codonNumb)
vertex_attr(graphData)
```


```{r}
maxMeans_64 <- conf[conf$Mean == max(conf$Mean)]
meanIsMedian_64_not0or1 <-  config[config$Mean == config$Median & config$Mean != 0.0 & config$Mean != 1.0]
meanIsMedian_64_0 <-  config[config$Mean == config$Median & config$Mean == 0.0]
meanIsMedian_64_1 <- config[config$Mean == config$Median & config$Mean == 1.0]
plot(meanIsMedian_64_0$Mean, fitness[[meanIsMedian_64_0$ids]])

fitness[meanIsMedian_64_1$ids]
```

```{r}
pos <- 944
fitnessValues <- fitness[[pos]]

# count number of generations that the cell lived
notNullValues <- length(which(fitnessValues > 0))

# if cell didn't die
if(notNullValues == length(fitnessValues)){
  # check if there are repetitive values
  counted <- rle(fitnessValues)
  counted$values[counted$lengths != 1]
}

```

```{r}
#fitnessRow <- fitness[[which.max(config$Mean)]]
geneNumb30 <- config[which(config$geneNumb == 30)]
geneNumb30Mean <- mean(geneNumb30$Mean)

geneNumb15 <- config[which(config$geneNumb == 15)]
geneNumb15Mean <- mean(geneNumb15$Mean)

t.test(geneNumb15$Mean, geneNumb30$Mean)

library(tidyverse)
tibble(config)
anovaData <- select(config, aarsLifeticksStartValue, geneNumb, Mean)
anovaData <- anovaData[which(anovaData$geneNumb == 30)]

anovaData <- select(config, id, aarsLifeticksStartValue, Mean)

library(psych)
description <- describeBy(anovaData, anovaData$aarsLifeticksStartValue)
description
boxplot(anovaData$Mean ~ anovaData$aarsLifeticksStartValue, main = "Boxplot", xlab = "Group (ltStartValue)", ylab = "Mean", outline = TRUE)

# Inter group variance

# Define number of subjects in each group
##n <- description[[1]]$n
n <- 4320#length(which(anovaData$aarsLifeticksStartValue == 2))

# Calculate group means
y_j <- tapply(anovaData$Mean, anovaData$aarsLifeticksStartValue, mean)

# Calculate the grand mean
y_t <- mean(y_j)

# Calculate the sum of squares
ss_a <- n*sum((y_j - y_t)^2)

# Intra group variance

# Create a separate vector of Means for each training group
y_i1 <- subset(anovaData$Mean, anovaData$aarsLifeticksStartValue == 2)
y_i2 <- subset(anovaData$Mean, anovaData$aarsLifeticksStartValue == 5)
y_i3 <- subset(anovaData$Mean, anovaData$aarsLifeticksStartValue == 10)
y_i4 <- subset(anovaData$Mean, anovaData$aarsLifeticksStartValue == 15)

# Subtract group means from the individual values
s_1 <- y_i1 - y_j[1]
s_2 <- y_i2 - y_j[2]
s_3 <- y_i3 - y_j[3]
s_4 <- y_i4 - y_j[4]

# Put everything back together into one vector
s_t <- c(s_1, s_2, s_3, s_4)

# Calculate the sum of squares using s_t
ss_sa <- sum(s_t^2)

# calculate F-Value

# Number of groups
a <- 4

# Define degrees of freedom
df_a <- a - 1
df_sa <- a*(n-1)

# Calculate mean squares using ss_a and ss_sa
ms_a <- ss_a / df_a
ms_sa <- ss_sa / df_sa

# Calculate the F-ratio
f_rat <- ms_a / ms_sa

f_rat

anovaResult <- aov(Mean ~ as.factor(aarsLifeticksStartValue), data = anovaData)
anovaSummary <- summary(anovaResult)

anovaSummary

library(mvoutlier)

#which(config$geneNumb == 30, arr.ind = FALSE, useNames = FALSE)
```






```{r}
#data <- tail(data$V1,length(data$V1)-20)
#data
#summary(data)
#data <- tail(data, 1000)

data <- config$Mean
norm <- rnorm(length(data), mean(data), sd(data))
chisq.test(data, norm)
```




```{r}
# for WEKA
conf <- config[which(config$codonNumb == 64)]
#nominalMeans <- config$Mean >
mainData <- data.frame(geneNumb = conf$geneNumb, initAaNumb = conf$initAaNumb, similarAars = conf$similarAars, maxAnticodonNumb = conf$maxAnticodonNumb, aarsLifeticksStartValue = conf$aarsLifeticksStartValue, livingAarsStartNumb = conf$livingAarsStartNumb, mean = conf$Mean)


cutResult = cut(config$Mean, 10, ordered_result = TRUE)
levels(cutResult)

fun <- function(listElement){
value <- listElement
if(listElement <= 0.1) value = 0.1
else if(listElement <= 0.2) value = 0.2
  else if(listElement <= 0.3) value = 0.3
  else if(listElement <= 0.4) value = 0.4
  else if(listElement <= 0.5) value = 0.5
  else if(listElement <= 0.6) value = 0.6
  else if(listElememt <= 0.7) value = 0.7
  else if(listElement <= 0.8) value = 0.8
  else if(listElement <= 0.9) value = 0.9
  else if(listElement <= 1.0) value = 1.0
return(value)
}


conf <- config[which(config$codonNumb == 64),]
# copy mean values into new columne and make them nominal
nominalMean <- conf$Max
nominalMean[nominalMean <= 0.1] <- 0.1
nominalMean[nominalMean <= 0.2 & nominalMean >0.1] <- 0.2
nominalMean[nominalMean <= 0.3 & nominalMean >0.2] <- 0.3
nominalMean[nominalMean <= 0.4 & nominalMean >0.3] <- 0.4
nominalMean[nominalMean <= 0.5 & nominalMean >0.4] <- 0.5
nominalMean[nominalMean <= 0.6 & nominalMean >0.5] <- 0.6
nominalMean[nominalMean <= 0.7 & nominalMean >0.6] <- 0.7
nominalMean[nominalMean <= 0.8 & nominalMean >0.7] <- 0.8
nominalMean[nominalMean <= 0.9 & nominalMean >0.8] <- 0.9
nominalMean[nominalMean <= 1.0 & nominalMean >0.9] <- 1.0
conf <- cbind(conf, nominalMean)


mainData <- data.frame(geneNumb = conf$geneNumb, initAaNumb = conf$initAaNumb, similarAars = conf$similarAars, maxAnticodonNumb = conf$maxAnticodonNumb, aarsLifeticksStartValue = conf$aarsLifeticksStartValue, livingAarsStartNumb = conf$livingAarsStartNumb, mean = conf$Mean)


#nominalConf <- lapply(conf$Mean, fun)

#nicePart <- config[codonNumb == 24][geneNumb == 30][Mean > 0.2]

#nominalConf <- lapply(nicePart[c(1:length(nicePart))]$Mean, fun)

#conf[which(config$Mean >= 0.1)]

#conf$Mean <= 0.1

fwrite(mainData, "G:/Hanna/data_affinity_64_numericMean.csv")
```









