---
title: "Anova Notebook"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

**Overview**
- load libraries
- load saved data and give overview
- living dead diagram (output seed <= 10)
- create subset with high survival rate treatments (10 survivors per treatment)

```{r include=FALSE}
library(data.table)
library(pander)
library(rcompanion)
library(multcompView)
panderOptions('knitr.auto.asis', FALSE)
#library(summarytools)
#library(ggplot2)
```

```{r}
load("config6FactL2029Out0120RandAndMaxL2029Out0110.RData")
config = config6FactL2029Out0120RandAndMaxL2029Out0110
```

```{r living dead diagram}

configLiving <- config[which(config$notNullValues == 100000 & config$outputSeed <= 10),]
configDead <- config[which(config$notNullValues < 100000 & config$outputSeed <= 10),]

livingDeadHist = function (living, dead, title){
deadHist <- hist(dead, plot = FALSE)
livingHist <- hist(living, plot = FALSE)
deadCounts <-deadHist$counts
deadCounts <- deadCounts[which(deadCounts != 0)]
livingCounts <- livingHist$counts
livingCounts <- livingCounts[which(livingCounts != 0)]

matrix = matrix(rbind(livingCounts, deadCounts),nrow = 2)
colnames(matrix)=c(levels(factor(dead)))
rownames(matrix) = c("living", "dead")
data_percentage=apply(matrix,2, function(x){x*100/sum(x,na.rm=T)})

print(matrix)
print(data_percentage)
barplot(data_percentage, col=c("green", "black") , border="black", xlab= title, cex.names = 1.4, cex.axis = 1.4)
legend("topright", legend = rownames(matrix), fill=c("green", "black") , ncol = 1, cex = 1.3)

}
livingTranslationTypes <- c(nrow(configLiving[which(configLiving$translationType == "random"),]), nrow(configLiving[which(configLiving$translationType == "affinity"),]), nrow(configLiving[which(configLiving$translationType == "max"),]))
deadTranslationTypes <- c(nrow(configDead[which(configDead$translationType == "random"),]), nrow(configDead[which(configDead$translationType == "affinity"),]),nrow(configDead[which(configDead$translationType == "max"),]))

matrix = matrix(rbind(livingTranslationTypes, deadTranslationTypes),nrow = 2)
colnames(matrix)=c("random", "affinity", "max")
rownames(matrix) = c("living", "dead")
data_percentage=apply(matrix,2, function(x){x*100/sum(x,na.rm=T)})

print(matrix)
print(data_percentage)



par(mfrow = c(2, 4), cex.lab = 1.4, oma = c(5,4,0,0) + 0.1,
          mar = c(4,1,2,4) + 0.1)


barplot(data_percentage, col=c("green", "black") , border="black", xlab= "Translation type", cex.names = 1.4, cex.axis = 1.4)
legend("topright", legend = rownames(matrix), fill=c("green", "black") , ncol = 1, cex = 1.3)


livingDeadHist(configLiving$geneNumb, configDead$geneNumb, "Number of genes")
livingDeadHist(configLiving$initAaNumb, configDead$initAaNumb, "Amino acids")
livingDeadHist(configLiving$similarAars, configDead$similarAars, "Similarity of aaRSs")
livingDeadHist(configLiving$aarsLifeticksStartValue, configDead$aarsLifeticksStartValue, "Lifeticks")
livingDeadHist(configLiving$livingAarsStartNumb, configDead$livingAarsStartNumb, "Number of living aaRSs")
livingDeadHist(configLiving$livingAarsSeed, configDead$livingAarsSeed, "Living aaRSs seed")


```
```{r treatments with 10 survivors}
# @Description 7 parameters are extracted from a config file. The means are collected into lists. Each list consists of the means of one parameter combination (output seeds 1 to 10). Either the mean of those means can be calculated or the means per list are counted (useful in the case of a living or dead data set). Is the unique(reducedConfig) line included the result is a list with one value per parameter combination. Otherwise the list is as long as the config file. One possible case is to choose all rows with parameter combinations that didn't lead to any dead cells.
# When the extracted parameters shall be different then there have to be some changes made.

lconfig <- configLiving[,c(16, 19:21, 23:25, 1)]


# @Before Set config variable. Comment/uncomment unique(reducedConfig) line and decide between means and lengths or both.
  config <- lconfig
  reducedConfig <- lconfig[,c(1:7)]  # without mean (needed when unique follows)
  #reducedConfig <- unique(reducedConfig) #skip this line if resulting list of means or lengths shall have the same length as config.

  summarizeByOutputSeed <- function (p1, p2, p3, p4, p5, p6, p7){
   config$mean[which(config$translationType == p1 & config$geneNumb == p2 & config$initAaNumb == p3 & config$similarAars == p4 & config$aarsLifeticksStartValue == p5 & config$livingAarsStartNumb == p6 & config$livingAarsSeed == p7)]
 }
 
 outputMeansOrdered <- sapply(1:nrow(reducedConfig), FUN = function(pos){i <- reducedConfig[pos,]; summarizeByOutputSeed(i[[1]], i[[2]], i[[3]], i[[4]], i[[5]], i[[6]], i[[7]])})

 # meansOfOutputMeans <- sapply(1: length(outputMeansOrdered), FUN = function(pos){mean(outputMeansOrdered[[pos]])})
 
 # List of counts of surviving cells per parameter combination
 lengthsOfOutputMeans <- sapply(1: length(outputMeansOrdered), FUN = function(pos){length(outputMeansOrdered[[pos]])})
 counts <- summary(as.factor(lengthsOfOutputMeans))
 counts
 
  # Choose all rows of treatments that have 10 surviving cells
 lconfig <- lconfig[lengthsOfOutputMeans == 10]
  
```

```{r reducedConfig for survival rate, warning=FALSE, results='asis'}
# @Before lconfig <- data to be analysed (only relevant rows plus mean at the end)

analysis = function (paramIndices){
  paramNumb <- length(paramIndices)
  config <- lconfig
  reducedConfig <- config[,paramIndices, with = FALSE] #lconfig[,..paramIndex]   
  reducedConfig <- unique(reducedConfig)  # treatments
  
  writeLines("\n")
  writeLines("**Treatments**\n")
  print(pander(reducedConfig))
  writeLines("\n")
  
  if (paramNumb == 1){
    sapply(1:length(paramIndices), FUN = function (index){print(pander(summary(factor(config[[paramIndices[index]]]))))})
  }
  if(paramNumb > 1){
    print(pander(summary(interaction(config[,paramIndices, with = FALSE]))))
  }
  
  # make a list of params 
  params <- data.table(config[[paramIndices[1]]])
  if(paramNumb > 1){
    sapply(2:paramNumb, FUN = function (index){assign('params', cbind(params, config[[paramIndices[index]]]), pos = 1)})
  }
  
  orderMeansByFactors = function (){
    summarize <- function (pos){
      fact <- reducedConfig[pos,]
     config$mean[which(params[,1] == fact[[1]] & eval(cond(2)) & eval(cond(3)) & eval(cond(4)) & eval(cond(5)) & eval(cond(6)) & eval(cond(7)))]
    }
  cond = function(i){
    if(i <= paramNumb){quote(params[,..i] == fact[[i]])}else{TRUE}
  }
    
    return (sapply(1:nrow(reducedConfig), FUN = function(pos){summarize(pos)}))
  }

  outputMeansOrdered = orderMeansByFactors()

  interaction(params[,c(1:paramNumb)])
 
  
  # use the lists of means to check if they are normally distributed
  normalityTestPValue <- sapply(1: length(outputMeansOrdered), FUN = function (pos) {if(length(outputMeansOrdered[[pos]]) > 1){norm <- rnorm(length(outputMeansOrdered[[pos]]), mean(outputMeansOrdered[[pos]]), sd(outputMeansOrdered[[pos]]))
  chisq.test(outputMeansOrdered[[pos]], norm)$p.value}else{0}})
  
  writeLines("\n")
  writeLines("**Normal distribution**\n")
  print(pander(normalityTestPValue))
  
  
  tests = function (param) {
    if(length(normalityTestPValue[which(normalityTestPValue > 0.05)]) == length(normalityTestPValue)){
    HomogeneityPValue <- bartlett.test(lconfig$mean ~ param)$p.value
    
    writeLines("\n")
    writeLines("**Homogeneity of Variance**\n")
    print(HomogeneityPValue)
    writeLines("\n")
    
    if(HomogeneityPValue <= 0.05){
      oneway <- oneway.test(lconfig$mean~param)
      
      writeLines("**oneway**\n")
      print(oneway$p.value)
      
      writeLines("\n")
      writeLines("**Posthoc**\n")
      posthoc <- pairwise.t.test(lconfig$mean, param, pool.sd = FALSE)
            posthoc <- posthoc$p.value
      print(pander(posthoc))
      posthoc <- fullPTable(posthoc)
      print(pander(multcompLetters(posthoc, compare="<", threshold = 0.05, Letters = letters, reversed = FALSE)))
      writeLines("\n")
      
    }else{
      oneway <- oneway.test(lconfig$mean~param)
      
      writeLines("**oneway**\n")
      print(oneway$p.value)
      
      writeLines("\n")
      writeLines("**Posthoc**\n")
      posthoc <- pairwise.t.test(lconfig$mean, param, pool.sd = TRUE)
      posthoc <- posthoc$p.value
      print(pander(posthoc))
      posthoc <- fullPTable(posthoc)
      print(pander(multcompLetters(posthoc, compare="<", threshold = 0.05, Letters = letters, reversed = FALSE)))
      writeLines("\n")
    }
  }else{# not normally distributed
      writeLines("**Fligner-Killeen**\n")
      fligner <- fligner.test(lconfig$mean ~ param)
      print(pander(fligner$p.value))
      
      writeLines("\n")
      writeLines("**Kruskal**\n")
      kruskal <- kruskal.test(lconfig$mean~param)
      print(pander(kruskal$p.value))
      writeLines("\n")
      
      writeLines("**Posthoc**\n")
      posthoc <- pairwise.wilcox.test(lconfig$mean, param)
            posthoc <- posthoc$p.value
      print(pander(posthoc))
      posthoc <- fullPTable(posthoc)
      print(pander(multcompLetters(posthoc, compare="<", threshold = 0.05, Letters = letters, reversed = FALSE)))
      writeLines("\n")
  }
  print(" ")
  }
  
  tests(param)
  
}




xy = function (p, indexlist){
    sapply(p:7, FUN = function (pos){
      indexlist <- rbind(indexlist, pos)
      #analysis(indexlist)
      print(indexlist)
      if(p < 7) {
        xy(p+1, indexlist)
      }
    })
}
xy(1, c())







x = function (p, indexlist, commands){
    sapply(p:7, FUN = function (pos){
      indexlist <- cbind(indexlist, pos)
      analysis(indexlist)
      print(indexlist)
      if(p < 7) {
        assign('commands', rbind(commands,data.table(p+1, list(indexlist))))
      }
    })
  print(commands)
  if(nrow(commands) >= 1){
    x(commands[1,1][[1]], commands[1,2][[1]], tail(commands, nrow(commands)-1))
  }
  
}
x(5, c(),data.table())




library(functional)

xxx = function (indexlist, commands){
  
  func = function (pos, indexlist, commands){
      indexlist <- cbind(indexlist, pos)
      print(indexlist)
  }
  
  newfunc <- Curry(func,indexlist=indexlist, commands = commands)

    

sapply(6:7, FUN = newfunc)

    }

xxx(c(), c())


indexlist = c()
commands = c()

x = function (p, indexlist){
  func = function (pos, indexlist){
      assign('indexlist', cbind(indexlist, pos), envir = .GlobalEnv)
      analysis(indexlist)
      print(indexlist)
      if(p < 7) {
        #assign('commands',  <- rbind(commands, data.table(p+1,list(indexlist)))
        assign('commands', rbind(commands,data.table(p+1, list(indexlist))), envir = .GlobalEnv)
      }
      print(commands)
  }
  
  cFunc = Curry(func, indexlist = indexlist)
  
    sapply(p:7, FUN = cFunc)
    
  
  if(nrow(commands) >= 1){
    x(commands[1,1][[1]], commands[1,2][[1]])
  }
  
}
x(5, c())









func = function (indexlist){
  
    print(rbind(c(indexlist),c(6)))
   
}

func(c(1,2), c())



  
sapply(1:7, FUN = function (pos1){
  indexlist <- c(pos1)
  analysis(indexlist)
  sapply(2:7, FUN = function (pos2){
    if(pos1 != pos2){
      indexlist <- cbind(indexlist, pos2)
      analysis(indexlist)
      sapply(3:7, FUN = function (pos3){
        indexlist <- cbind(indexlist, pos3)
        analysis(indexlist)
        #........
      })
    }})
  })
    
 
```

```{r eval=FALSE, include=FALSE}

# strong effect
CohenD(lnconfig$mean[which(lnconfig$translationType == "affinity")], lnconfig$mean[which(lnconfig$translationType == "random")])
# 0.05...
rsquare(lm(lnconfig$mean ~ factor(lnconfig$translationType)), lnconfig)



pairwise.t.test(lnconfig$mean, lnconfig$translationType, pool.sd = FALSE)
pairwise.t.test(lnconfig$mean, lnconfig$geneNumb, pool.sd = FALSE)
pairwise.t.test(lnconfig$mean, lnconfig$initAaNumb, pool.sd = FALSE)
pairwise.t.test(lnconfig$mean, lnconfig$similarAars, pool.sd = FALSE)
pairwise.t.test(lnconfig$mean, lnconfig$aarsLifeticksStartValue, pool.sd = FALSE)
pairwise.t.test(lnconfig$mean, lnconfig$livingAarsStartNumb, pool.sd = FALSE)
pairwise.t.test(lnconfig$mean, lnconfig$livingAarsSeed, pool.sd = FALSE)





CohenD(lnconfig$mean[lnconfig$initAaNumb == 17],lnconfig$mean[lnconfig$initAaNumb == 23], pooled = FALSE)  #0.1397491 effect size < 0.2

rsquare(lm(lnconfig$mean ~ factor(lnconfig$initAaNumb)), lnconfig)   #0.003533606


library(DescTools)
library(modelr)



 #normalityTestPValue <- data.frame(normalityTestPValue)
 #normalityTestPValue$normalityTestPValue[which(normalityTestPValue < 0.05)]
 # -> Either too less observations are available for a specific parameter combination or it is normal distributed. The observations of one combi always lay very near together or are even the same.
 
 reducedConfig = cbind(reducedConfig, lengthsOfOutputMeans)
 
 kruskal.test(reducedConfig$lengthsOfOutputMeans ~ interaction(factor(reducedConfig$initAaNumb),factor(reducedConfig$geneNumb)))
 
 
 
  
 #outputMeansOrdered <- split(as.vector(outputMeansOrdered), seq(nrow(reducedConfig)))
 
 #meansOfOutputMeans <- sapply(1: length(outputMeansOrdered), FUN = function(pos){mean(outputMeansOrdered[[pos]])})
 
 print("Anova")
      result <- aov(lnconfig$mean ~ factor(param))
      print(summary(result)[[1]][["Pr(>F)"]][1]) 
      
      print("Post hoc")
      pairwise.t.test(lnconfig$mean, factor(param), pool.sd = TRUE)
```


```{r eval=FALSE, include=FALSE}
interact <- interaction(factor(conf[,2]), factor(conf[,3]), factor(conf[,4]), factor(conf[,5]), factor(conf[,6]), factor(conf[,7]), factor(conf[,8]))
lengths <- tapply(conf$mean, interact, length)
lengths <- data.frame(lengths)
interact <- interact[which(lengths$lengths > 0)]
lengths <- lengths$lengths[which(lengths$lengths > 0)]
conf <- cbind(conf, lengths)
pairwise.t.test(lengths , factor(conf$geneNumb), p.adjust.method = "bonferroni")

tapply(configLiving$mean, factor(interact), function (data) {norm <- rnorm(length(data), mean(data), sd(data))
chisq.test(data, norm)$p.value})

tapply(configLiving$mean, factor(interact), function (x) shapiro.test(x)$p.value)

tapply(configLiving$mean, factor(configLiving$initAaNumb), function (x) shapiro.test(x)$p.value)



plot(factor(interact), configLiving$mean)
goodFitnessInteractions <- interact[configLiving$mean > 0.2]


plot(0, 0, xlim = c(0, 100), ylim = c(0, 200))

x = 0
lengths <- tapply(conf$mean, interact, length)
lengths <- data.frame(lengths)
plot(lengths)

aovResult <- aov(lengths$lengths[which(lengths$lengths > 0)] ~ unique(interact))
aovResult
summary(aovResult)
TukeyHSD(aovResult)
pairwise.t.test(lengths$lengths[which(lengths$lengths > 0)] , unique(interact), p.adjust.method = "bonferroni")
boxplot(lengths$lengths[which(lengths$lengths > 0)] ~ unique(interact))

```




```{r eval=FALSE, include=FALSE}
aovResult <- aov(mean ~ factor(initAaNumb)+factor(aarsLifeticksStartValue)+factor(livingAarsStartNumb)+factor(livingAarsSeed)                                       , data = configLiving)
aovResult
summary(aovResult)
tuc <- TukeyHSD(aovResult)
tuc$`factor(initAaNumb)`[,4][which(tuc$`factor(initAaNumb)`[,4]< 0.05)]

aovResult <- aov(mean ~ factor(interact), data = configLiving)
aovResult$model

interact = interaction(configLiving$initAaNumb,configLiving$geneNumb, sep = ".")
bartlett.test(configLiving$mean ~ interact)

pairwise.t.test(configLiving$mean, factor(interact), pool.sd = FALSE)

tapply(configLiving$mean, factor(interact), function (x) shapiro.test(x)$p.value)

CohenD(configLiving$mean[configLiving$initAaNumb == 17],configLiving$mean[configLiving$initAaNumb == 23])

rsquare(lm(configLiving$mean ~ factor(configLiving$initAaNumb)), configLiving)

library(modelr)

```


```{r eval=FALSE, include=FALSE}
x <-  0
addPoint = function (data, xValue){
  mci <- MeanCI(data)
  print(mci[1])
  points(xValue, mci[1])
  ErrBars(mci[2], mci[3], xValue)
 
}
plot(0, mci[1], xlim = c(0, 2), ylim = c(0, 0.3))
x <- x+0.2
print(x)
addPoint(configLiving$mean[configLiving$translationType == "affinity"], x)
x <- x+0.2
print(x)
addPoint(configLiving$mean[configLiving$translationType == "random"], x)
x <- x+0.2
print(x)
addPoint(configLiving$mean[configLiving$livingAarsStartNumb == 10], x)
x <- x+0.2
print(x)
addPoint(configLiving$mean[configLiving$geneNumb == 10], x)
x <- x+0.2
print(x)
addPoint(configLiving$mean[configLiving$geneNumb == 20], x)
x <- x+0.2
print(x)
addPoint(configLiving$mean[configLiving$geneNumb == 30], x)
x <- x+0.2




```


```{r print levels of data, eval=FALSE, include=FALSE}
data = config

levelsOfData = function (x){
  levels(factor(x))
}
levelsOfData(data$translationType)
levelsOfData(data$mrnaSeed)
levelsOfData(data$codonNumb)
levelsOfData(data$geneNumb)
levelsOfData(data$geneNumb)
levelsOfData(data$initAaNumb)
levelsOfData(data$similarAars)
levelsOfData(data$maxAnticodonNumb)
levelsOfData(data$aarsLifeticksStartValue)
levelsOfData(data$livingAarsStartNumb)
levelsOfData(data$livingAarsSeed)
levelsOfData(data$outputSeed)

```

```{r test for normal distribution, eval=FALSE, include=FALSE}
# affinity vs. random 
anvSet1 <- config[which(livingAarsSeed <= 24 & outputSeed <= 10)]  
data <- anvSet1$mean[which(anvSet1$translationType == "random")]
norm <- rnorm(length(data), mean(data), sd(data))
chisq.test(data, norm)

data <- anvSet1$mean[which(anvSet1$translationType == "affinity")]
norm <- rnorm(length(data), mean(data), sd(data))
chisq.test(data, norm)

# Anova for translation type affinity vs. random
anovaResult <- aov(anvSet1$mean ~ factor(translationType), data = anvSet1)
# summary, boxplot and t-test
summary(anovaResult)
boxplot(anvSet1$mean ~ factor(translationType), data = anvSet1)
t.test(anvSet1$mean[which(anvSet1$livingAarsSeed <= 24 & anvSet1$outputSeed <= 10 & anvSet1$translationType == "affinity")], anvSet1$mean[which(anvSet1$livingAarsSeed <= 24 & anvSet1$outputSeed <= 10 & anvSet1$translationType == "random")])

# Anova for translatin type affinity vs. random with living cells
anovaResult <- aov(anvSet1$mean ~ factor(translationType), data = anvSet1)
# summary, boxplot and t-test
summary(anovaResult)
boxplot(anvSet1$mean ~ factor(translationType), data = anvSet1)
t.test(anvSet1$mean[which(anvSet1$livingAarsSeed <= 24 & anvSet1$outputSeed <= 10 & anvSet1$translationType == "affinity")], anvSet1$mean[which(anvSet1$livingAarsSeed <= 24 & anvSet1$outputSeed <= 10 & anvSet1$translationType == "random")])


# post hoc
TukeyHSD(anovaResult)


# Anova with all
anovaResult <- aov(mean ~ factor(translationType) + factor(initAaNumb) + factor(geneNumb) + factor(aarsLifeticksStartValue) + factor(livingAarsStartNumb) + factor(livingAarsSeed) + factor(similarAars), data = anvSet1)
summary(anovaResult)
TukeyHSD(anovaResult)
# livingAarsSeed 20-21 is not significant as well as aarsLifeticksStartValue 2-5
# test aarsLifeticksStartvalue 2-5
anvSet2 <- config[which(livingAarsSeed <= 24 & outputSeed <= 10 & (aarsLifeticksStartValue == 2 | aarsLifeticksStartValue == 5))]   
anovaResult <- aov(mean ~ factor(translationType) + factor(initAaNumb) + factor(geneNumb) + factor(aarsLifeticksStartValue) + factor(livingAarsStartNumb) + factor(livingAarsSeed) + factor(similarAars), data = anvSet2)
# summary, boxplot
summary(anovaResult)
TukeyHSD(anovaResult)   

anovaResult <- aov(mean ~ factor(translationType) + factor(initAaNumb) + factor(aarsLifeticksStartValue), data = anvSet2)
# summary, boxplot
summary(anovaResult)
TukeyHSD(anovaResult)

anovaResult <- aov(mean ~ factor(aarsLifeticksStartValue), data = anvSet2)
# summary, boxplot
summary(anovaResult)
tuc <- TukeyHSD(anovaResult)

tuc <- tuc$`factor(aarsLifeticksStartValue)` 


anovaResult <- aov(mean ~ factor(initAaNumb) + factor(geneNumb) + factor(aarsLifeticksStartValue) + factor(livingAarsStartNumb) + factor(similarAars), data = anovaData)

anovaResult <- aov(mean ~  factor(aarsLifeticksStartValue), data = anvSet1)

plot(anovaResult$residuals, col = anvSet1$initAaNumb)
plot(anovaResult, col = anvSet1$initAaNumb)

anvSet2 <- config[which(livingAarsSeed == 20)]
colourPlots <- list(config, anvSet2)
```

```{r boxplot, eval=FALSE, include=FALSE}
plotBoxes = function (x,y, title){
boxes <- boxplot(x ~  factor(y), col = "yellow")
title(title)

mn.t <- tapply(x, y, mean)
sd.t <- tapply(x, y, sd)
xi <- seq(boxes$n)
points(xi, mn.t, col = "blue", pch = 18)
arrows(xi, mn.t - sd.t, xi, mn.t + sd.t,
       code = 3, col = "blue", angle = 75, length = .1)
}
plotBoxes(anvSet1$mean,anvSet1$aarsLifeticksStartValue, "Comparing fitness of various lifeticks start values")

boxes <- boxplot(mean ~ factor(initAaNumb) * factor(aarsLifeticksStartValue) * factor(similarAars) * factor(livingAarsSeed), data = configLiving)

mn.t <- tapply(mean, (factor(initAaNumb) * factor(aarsLifeticksStartValue) * factor(similarAars) * factor(livingAarsSeed), data = configLiving), mean)
sd.t <- tapply(mean, factor(initAaNumb) * factor(aarsLifeticksStartValue) * factor(similarAars) * factor(livingAarsSeed), data = configLiving, sd)
xi <- seq(boxes$n)
points(xi, mn.t, col = "blue", pch = 18)
arrows(xi, mn.t - sd.t, xi, mn.t + sd.t,
       code = 3, col = "blue", angle = 75, length = .1)


```

