---
title: "Load and Save RData files"
output: html_notebook
---

```{r save, eval=FALSE, cache=TRUE, include=FALSE}
config6FactL2029Out0110L2529Out1120RandL2024Out0110 <- rbind(config6FactL0009Out10L0509Out1120, newConfig)

save(config6FactL2029Out0110L2529Out1120RandL2024Out0110, file = "E:/Hanna/R/ANOVA/config6FactL2029Out0110L2529Out1120RandL2024Out0110.RData") 
#save(fitness6FactorsOut1120, file = "G:/Hanna/R/ANOVA/fitness6FactorsOut1120.RData") 



save(outputMeansOrdered, file ="C:/Users/feroc/MagentaCLOUD/MasterThesis/config6FactL2029Out0120RandAndMaxL2029Out0110_OutputMeansOrderedByNotNullValues.RData")

```

```{r load}
load("E:/Hanna/R/ANOVA/config6FactL2029Out0110L2529Out1120RandL2024Out0110.RData")

# load("G:/Hanna/R/ANOVA/config6FactorsOut1120.RData")
# load("G:/Hanna/R/ANOVA/config6FactorsOut10.RData")
# load("G:/Hanna/R/ANOVA/fitness6FactorsOut1120.RData")

```

```{r save fitness}
fitnessRandL2024Out0110 <- fitness
originalFitnessRandL2024Out0110 <- originalFitnessData

save(fitnessRandL2024Out0110, file= "E:/Hanna/R/ANOVA/RandL2024Out0110.RData")
save(originalFitnessRandL2024Out0110, file= "E:/Hanna/R/ANOVA/originalFitnessRandL2024Out0110.RData")
```


```{r write descriptive statistics to file, eval=FALSE, include=FALSE}
attach(config)
statsToPrint <- data.table(mean, sd, min, q1, med, q3, max, mad, iqr, cv, skewness, se.skewness, kurtosis, notNullValues, simulationSteps)
colnames(statsToPrint) <- c("mean", "sd", "min", "q1", "med", "q3", "max", "mad", "iqr", "cv", "skewness", "se.skewness", "kurtosis", "notNullValues", "simulationSteps")
fwrite(statsToPrint, "G:/Hanna/stats_64_172023aa_ 10outSeed_5livingSeed.csv")
rm(statsToPrint)
detach(config)
```
